# CameraDetection â radar_camera â radar_fusion
# PUB direction: radar_camera â /camera/detection â radar_fusion

std_msgs/Header header
geometry_msgs/Point hero_position
float64 hero_confidence
geometry_msgs/Point engine_position
float64 engine_confidence
geometry_msgs/Point infantry_3_position
float64 infantry_3_confidence
geometry_msgs/Point infantry_4_position
float64 infantry_4_confidence
geometry_msgs/Point sentry_position
float64 sentry_confidence
geometry_msgs/Point drone_position
float64 drone_confidence
