enemy_color: "blue"
robot_class_id:
  hero_red: 0
  engineer_red: 2
  infantry3_red: 4
  infantry4_red: 6
  sentry_red: 8
  drone_red: 10
  hero_blue: 1
  engineer_blue: 3
  infantry3_blue: 5
  infantry4_blue: 7
  sentry_blue: 9
  drone_blue: 11
model_path: "/workspace/ros_ws/src/radar_camera/config/camera_inference_model.onnx"
model_input_width: 1280
model_input_height: 1280
conf_threshold: 0.6
nms_threshold: 0.45
min_length_width_rate: 0.8
max_length_width_rate: 1.5
use_openvino: 1
num_classes: 12
internal_parameter:
  camera_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]
extrinsic_parameter:
  rotation: [0.0, 0.0, 0.0]
  translation: [0.0, 0.0, 0.0]
topic_name: "/radar_camera/robot_pose"