radar_camera_node:
  ros__parameters:
    # 红方相机在地图坐标系中的位姿
    # 由红方雷达初始位姿 (tx=-14, tz=4, pitch=-10°) + 传感器外参推算
    # 雷达在相机左8cm高2cm => 相机在雷达右-0.08m低-0.02m
    rotation: [0.0, -0.17453, 0.0]
    translation: [-13.9965, -0.0800, 3.9803]
