# Odin 驱动配置 — SLAM 建图模式 (custom_map_mode=1)
# 赛前离线走图一次，产出 .bin 地图供 odin_driver_relocalization.yaml 使用
# 走图结束后执行 ./set_param.sh save_map 1 保存地图
# 用法: ros2 launch odin_ros_driver odin1_ros2.launch.py config_file:=此文件路径

register_keys:
  strict_usb3.0_check: 0
  use_host_ros_time: 0
  streamctrl: 1

  sendrgbcompressed: 0
  sendrgb: 0
  sendrgbundistort: 0
  sendimu: 0
  enable_imu_smooth: 0

  sendodom: 1
  send_odom_baselink_tf: 1

  senddtof: 1
  cloud_raw_confidence_threshold: 35
  dtof_fps: 100

  sendcloudslam: 1
  sendcloudrender: 0
  senddepth: 0
  sendreprojection: 0
  sendoverlay: 0

  recorddata: 0
  devstatuslog: 1
  save_log: 0
  pubintensitygray: 0
  showpath: 0
  showcamerapose: 0

  custom_map_mode: 1
  custom_init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  relocalization_map_abs_path: ""
  mapping_result_dest_dir: ""
  mapping_result_file_name: ""
  sendimagemask: 0
  image_mask_abs_path: ""
  resetalgo: 0
