radar_camera_node:
  ros__parameters:
    enemy_color: "blue"
    hero_red: 0
    engineer_red: 1
    infantry3_red: 2
    infantry4_red: 3
    sentry_red: 4
    drone_red: 5
    hero_blue: 6
    engineer_blue: 7
    infantry3_blue: 8
    infantry4_blue: 9
    sentry_blue: 10
    drone_blue: 11
    model_path: "/workspace/ros_ws/src/radar_camera/config/camera_inference_model.onnx"
    device_name: "CPU"
    model_input_width: 1280
    model_input_height: 1280
    conf_threshold: 0.6
    min_length_width_rate: 0.8
    max_length_width_rate: 1.5
    use_openvino: true
    num_classes: 12
    mesh_path: "/workspace/ros_ws/src/radar_camera/model"
    camera_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    distortion_coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    translation: [0.0, 0.0, 0.0]
    pub_topic_name: "/radar_camera/robot_pose"
    shm_name: "/hikcamera_shm"
    width: 5472
    height: 3648
